;
;
;
BDOS		EQU 0005H	;STANDARD CP/M ENTRY
CONIN		EQU 1		;CONSOLE INPUT FUNCTION
;
		ORG 0100H	;BASE OF TPA
;
NEXTC:		MVI C, CONIN	;READ NEXT CHARACTER
		CALL	BDOS	;RETURN CHARACTER IN <A>
		CPI	'*'	;END OF PROCESSING?
		JNZ	NEXTC	;LOOP IF NOT
		RET		;RETURN TO CCP
		
;		END